alias ls="exa --icons --grid --colour=auto --sort=type --group-directories-first --header --modified --created --git --binary --group"
alias la="ls -a"
alias ll="ls -al"
alias peaclock="peaclock --config-dir ~/.config/peaclock"
alias pdf="$HOME/Repos/termpdf.py/termpdf.py 2>/dev/null"
alias horario="termpdf /home/antonio/OneDrive/cursos/curso-2023-2024/horarios/horario-segundo-cuatrimestre.pdf 2>/dev/null"
alias calendario="zathura ~/OneDrive/cursos/curso-2023-2024/horarios/calendario.pdf 2>/dev/null"
alias img="kitty +kitten icat"
alias doraemon="mpv -ao=pulse ~/Videos/VIAJE\ AL\ MISMO\ PLANETA.mp4"
alias mhr="img ~/Pictures/memes/mangel.jpeg"
alias chess="cli-chess"
alias nvidia-settings="nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings"
alias bc="bc -l $XDG_CONFIG_HOME/bcinit"
